### ISSUE TITLE
sonarr.py TypeError when logging

### ISSUE THREAD

**Issue by oilervoss** [Adman1020/Elsewherr#8]
It worked for a couple of times and then the sonarr.py gives and exception:

```
Traceback (most recent call last):
  File "/usr/src/myapp/sonarr.py", line 73, in <module>
    logging.info("show IMDB ID: "+show["imdbId"])
KeyError: 'imdbId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/myapp/sonarr.py", line 79, in <module>
    logging.info("Getting the IMDB failed: " + KeyError)
TypeError: can only concatenate str (not "type") to str
```

**Comment by oilervoss** [comment]
Sorry. Wrong repo. I should put it on https://github.com/LiamAird/Elsewherr

**Comment by oilervoss** [comment]
I had one exception when running sonarr.py https://github.com/Adman1020/Elsewherr/issues/8

I have two instances for each Radarr and Sonarr, one for HD, another for 4k. The issue only happens when running sonarr.py on my larger library (HD). I have an orphan imdb series there (https://thetvdb.com/series/follow-the-food), i.e., there is tvdb entry but no imdb.

**Comment by Tharic99** [comment]
So I've seen similar errors on the Radarr side where there is an orphaned tmdb record. It was for an untitled Pirates of the Caribbean reboot. It generated a similar KeyError from python. 

Looks like some kind of error checking that the movie/series exists on tmdb/imdb neds to be improved to resolve this. The workaround for me at least on the Radarr side was to remove the orphaned record.
